name: client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  parse_server_sdk_flutter: ^3.1.3
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  username_gen: ^1.0.4
  built_collection: ^5.0.0
  built_value: ^8.4.0
  rive: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=1.0.0 <3.0.0'
  built_value_generator: ^8.4.2
  pedantic: ^1.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
